#
# config.yml: Main configuration file for Kometa.
#

#
# Define the libraries
#
libraries:
  #
  # Define scheduled movie collections
  #
  Scheduled:
    # Define target Plex library
    library_name: Movies

    # Define where to store missing movies report
    report_path: config/missing/scheduled-report.yml

    # Define scheduled 'Movies' library template variable overrides
    template_variables:
      use_separator: false

    # Define scheduled 'Movies' library collections
    collection_files:
      # Define folder with scheduled 'Movies' library collections
      - folder: /config/scheduled/

      # Dynamic collections based on the years available in your library, sorted by critic rating to create a "best of"
      - default: year
        template_variables:
          limit: 50
          sort_by: critic_rating.desc
          data:
            starting: current_year-1
            ending: current_year-1
          summary_format: Top <<limit>> movies of <<key>>. Sorted by critic rating.
          collection_section: "010"
          schedule: range(01/01-04/01)

    # Define scheduled 'Movies' library settings
    settings:
      delete_not_scheduled: true
      asset_directory: config/assets

  #
  # Define 'Movies' library collections
  #
  Movies:
    # Define where to store missing movies report
    report_path: config/missing/movies-report.yml

    # Define 'Movies' library template variable overrides
    template_variables:
      use_separator: false

    # Define 'Movies' library collections
    collection_files:
      # Define folder with 'Movies' library collections
      - folder: config/movies/

      #
      # Define 'Movies' library default collections
      #

      # Dynamic collections based on the content ratings available in your library
      - default: content_rating_us

      # Collections with items that are based on or inspired by various media outlets, such as books or video games
      - default: based
        template_variables:
          summary_true_story: Films based on or inspired by a true story.
          summary_book: Films based on or inspired by a book.
          summary_video_game: Films based on or inspired by a video game.
          summary_comic: Films based on or inspired by a comic.
          schedule: all[weekly(sunday), hourly(05-07)]

      # Dynamic collections based on the studios available in your library
      - default: studio
        template_variables:
          minimum_items: 10

      # Dynamic collections based on the decades available in your library, sorted by critic rating to create a "best of"
      - default: decade
        template_variables:
          limit: 100
          limit_1970: 25
          summary_format: Top <<limit>> movies of the <<key>>s. Sorted by critic rating.
          summary_1970: Top <<limit_1970>> movies of the <<key>>s. Sorted by critic rating.
          minimum_items: 25

      # Dynamic collections based on the genres available in your library
      - default: genre
        template_variables:
          sort_by: title.asc
          exclude: # In genre.yml config
            - Horror
            - War
            - Western
            - Spy
            - Sport
          minimum_items: 10

      # Collections based on IMDb charts
      - default: imdb
        template_variables:
          use_lowest: false
          order_top: 3
          order_popular: 3

      # Collections based on TMDb charts
      - default: tmdb
        template_variables:
          limit_popular: 50
          visible_library_popular: true
          visible_home_popular: true
          visible_shared_popular: true

      # Collections based on lists from Letterboxd
      - default: letterboxd
        template_variables:
          use_imdb_top_250: true
          use_oscars: true
          use_cannes: true
          visible_library_top_250: true
          visible_home_top_250: true
          visible_shared_top_250: true

      # Dynamic seasonal collections based on holidays
      - default: seasonal
        template_variables:
          emoji: ""
          schedule_independence: range(06/28-07/05)
          schedule_labor: range(09/01-09/05)
          schedule_thanksgiving: range(11/01-11/24)
          schedule_veteran: range(11/01-11/12)
          imdb_list_veteran: https://www.imdb.com/list/ls561621160/
          # These default collections are defined in the seasonal.yml config
          exclude:
            - christmas
            - easter
            - halloween
            - mother
            - patrick
            - thanksgiving
            - valentine
            - years

      # Collections based on Tautulli/Plex charts
      - default: tautulli
        template_variables:
          collection_section: "020_1"
          list_days: 30
          list_size: 25
          list_minimum: 0
          summary_popular: A collection of the most watched movies on this Plex server.

      # Collections based on Trakt charts
      - default: trakt
        template_variables:
          use_collected: false
          use_recommended: false
          use_watched: false
          order_popular: 4
          order_trending: 4
          schedule: weekly(monday)

      # Collections based on popular movie universes, such as the Marvel Cinematic Universe or Wizarding World
      - default: universe
        template_variables:
          collection_section: "106"
          trakt_list_mcu: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe
          trakt_list_dcu: https://trakt.tv/users/lampshadetricky/lists/dc-extended-universe
          trakt_list_trek: https://trakt.tv/users/rzepkowski/lists/star-trek-movies
          trakt_list_avp: https://trakt.tv/users/liudvikas/lists/aliens-predators-movies
          minimum_items: 3
          append_data:
            star: Star Wars Saga
            trek: Star Trek Universe
            xmen: X-Men Collection
          # These default collections are defined in the franchise.yml config
          exclude:
            - marvel

      # Collections based on other charts, e.g. Steven Lu's popular movies and top 10 pirated movies of the week
      - default: other_chart
        template_variables:
          visible_library_pirated: true
          visible_home_pirated: true
          visible_shared_pirated: true
          use_anidb: false
          use_commonsense: false
          use_stevenlu: false

    #
    # Define 'Movies' library overlays
    #
    schedule_overlays: hourly(05-07)
    remove_overlays: false
    overlay_files:
      - file: config/overlays/top.yml
      - file: config/overlays/background.yml
      - default: mediastinger
        template_variables:
          file: config/overlays/bottom-left/mediastinger-bottom-left.png
          vertical_align: bottom
          vertical_offset: 0
          horizontal_align: right
          horizontal_offset: 0
          back_width: 1000
          back_height: 1500
          back_color: "#0000"

      # Resolution in the upper left corner in 45 degree format
      - default: resolution
        template_variables:
          file: config/overlays/resolution-top-left-45deg/<<overlay_name>>.png
          horizontal_align: left
          horizontal_offset: 0
          vertical_offset: 0
          vertical_align: top
          final_horizontal_offset: 0
          final_vertical_offset: 0
          back_width: 1000
          back_height: 1500
          back_color: "#0000"

      # Audio in the upper left corner in 45 degree format
      - default: audio_codec
        template_variables:
          file: config/overlays/audio-top-left-45deg/<<key>>.png
          horizontal_align: left
          horizontal_offset: 0
          vertical_offset: 0
          vertical_align: top
          back_width: 1000
          back_height: 1500
          back_color: "#0000"

    #
    # Define 'Movies' library settings
    #
    settings:
      show_missing_assets: false

    #
    # Define 'Movies' library operations
    #
    operations:
      schedule: all[weekly(monday|thursday|saturday), hourly(05-07)]
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: trakt_user
      assets_for_all: true

  #
  # Define TV show collections
  #
  TV Shows:
    # Define where to store missing TV shows report
    report_path: config/missing/tv-shows-report.yml

    # Define 'TV Shows' library template variable overrides
    template_variables:
      use_separator: false

    #
    # Define 'TV Shows' library collections
    #
    collection_files:
      # Define folder with 'TV Shows' library collections
      - folder: config/shows/

      # Define with scheduled 'TV Shows' library collections
      - file: config/scheduled/emmy.yml

      #
      # Define 'TV Shows' library default collections
      #

      # Dynamic collections based on the content ratings available in your library
      - default: content_rating_us

      # Dynamic collections based on the studios available in your library
      - default: studio
        template_variables:
          minimum_items: 10
          exclude: # In networks.yml config
            - HBO

      # Collections based on popular TV show franchises
      - default: franchise

      # Dynamic collections based on the genres available in your library
      - default: genre
        template_variables:
          sort_by: title.asc
          minimum_items: 2

      # Collections based on IMDb charts
      - default: imdb
        template_variables:
          use_lowest: false
          order_top: 3
          order_popular: 3

      # Collections based on TMDb charts
      - default: tmdb
        template_variables:
          limit_popular: 50
          visible_library_popular: true
          visible_home_popular: true
          visible_shared_popular: true

      # Collections based on Tautulli/Plex charts
      - default: tautulli
        template_variables:
          list_days: 30
          list_size: 25
          list_minimum: 0
          summary_popular: A collection of the most watched movies on this Plex server.
          collection_section: "020_1"

      # Collections based on Trakt charts
      - default: trakt
        template_variables:
          use_collected: false
          use_recommended: false
          use_watched: false
          order_popular: 4
          order_trending: 4
    #
    # Define 'TV Shows' library overlays
    #
    schedule_overlays: hourly(05-07)
    remove_overlays: false
    overlay_files:
      - file: config/overlays/top.yml
      - file: config/overlays/status.yml
      - file: config/overlays/network-fallback.yml
      - default: network
        template_variables:
          horizontal_align: left
          horizontal_offset: 0
          vertical_offset: 0
          vertical_align: top
          back_width: 1000
          back_height: 1500
          file: config/overlays/network-top-left/<<key>>.png
          back_color: "#0000"
      - default: studio
        template_variables:
          horizontal_align: left
          horizontal_offset: 0
          vertical_align: top
          vertical_offset: 0
          back_width: 1000
          back_height: 1500
          file: config/overlays/studio-top-left/<<key>>.png
          back_color: "#0000"
      - default: streaming
        template_variables:
          horizontal_align: left
          horizontal_offset: 0
          vertical_offset: 0
          vertical_align: top
          back_width: 1000
          back_height: 1500
          file: config/overlays/streaming-top-left/<<key>>.png
          back_color: "#0000"

    #
    # Define 'TV Shows' library settings
    #
    settings:
      delete_not_scheduled: true
      asset_directory: config/assets

    #
    # Define 'TV Shows' library operations
    #
    operations:
      schedule: all[weekly(monday|thursday|saturday), hourly(05-07)]
      mass_genre_update: tmdb
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_user_rating_update: trakt_user

#
# Define movie and TV playlists
#
playlist_files:
  - file: config/playlists/playlists.yml
  - default: playlist
    # template_variables:
    #   # These default playlists are defined in the playlist.yml config
    #   exclude:
    #     - dragonball
    #     - xmen
  - playlist_sync_to_users: all

#
# Define global settings
#
settings:
  cache: true
  cache_expiration: 30
  asset_directory: config/assets
  asset_folders: false
  asset_depth: 1
  create_asset_folders: false
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  save_report: true
  tvdb_language: eng
  ignore_ids:
    - 232618
    - 156249
    - 241239
    - 71365
    - 84200
  ignore_imdb_ids: tt0096548,tt0214341,tt4834232,tt0088484,tt0090509,tt0092324,tt0280249,tt4093826,tt1758429,tt0203082
  item_refresh_delay: 0
  playlist_report: true
  playlist_sync_to_users: all
  verify_ssl: true
  custom_repo:
  overlay_artwork_filetype: jpg
  overlay_artwork_quality: 75
  check_nightly: true
  show_unconfigured: true
  playlist_exclude_users:
  run_order:
    - operations
    - metadata
    - collections
    - overlays

#
# Define service connections
#
plex:
  url: http://localhost:32400
  token: abc123
  timeout: 60
  db_cache: 1024
  clean_bundles: false
  empty_trash: false
  optimize: false
tautulli:
  url: http://localhost:8181
  apikey: abc123
notifiarr:
  apikey: abc123
webhooks:
  error:
  version:
  run_start:
  run_end:
  changes:
tmdb:
  apikey: abc123
  language: en
  cache_expiration: 60
  region: US
radarr:
  url: http://localhost:32788
  token: abc123
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: /movies
  monitor: false
  availability: announced
  quality_profile: HD-1080p
  tag: kometa
  search: false
  radarr_path: /movies
  plex_path: /volume1/movies
sonarr:
  url: http://localhost:32789
  token: abc123
  add_missing: false
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: /tv
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag: kometa
  search: false
  cutoff_search: false
  sonarr_path: /tv
  plex_path: /volume1/tv
trakt:
  client_id: abc123
  client_secret: abc123
  authorization:
    access_token: abc123
    token_type: Bearer
    expires_in: 101010
    refresh_token: abc123
    scope: public
    created_at: 101010
  pin:
mdblist:
  apikey: abc123
  cache_expiration: 60
omdb:
  apikey: abc123
  cache_expiration: 60
github:
  token: abc123
mal:
  client_id: abc123
  client_secret: abc123
  localhost_url: http://localhost/
  authorization:
    access_token: abc123
    token_type: Bearer
    expires_in: 101010
    refresh_token: abc123
  cache_expiration: 60
