#!/usr/bin/env python3

#
# Copyright 2025-2026 Scott Gigawatt
#
# Licensed under the Apache License, Version 2.0.
#
# editor-schema.py: Generate and validate the pinned Kometa editor configuration schema.
#
# Purpose: Add narrowly scoped runtime-supported fields missing from upstream validation.
# Usage: make validate-editor
#

"""Keep editor diagnostics strict without rejecting supported Kometa customization."""

import copy
import json
import os
import re
import urllib.request
from pathlib import Path

from jsonschema import validators
from ruamel.yaml import YAML


def build_schema(upstream: dict) -> dict:
    """Extend the pinned schema only at verified compatibility gaps.

    Args:
        upstream: The unmodified schema from the configured Kometa release.

    Returns:
        An independent schema retaining upstream restrictions and typo detection.
    """
    schema = copy.deepcopy(upstream)
    definitions = schema["definitions"]
    seasonal = definitions["seasonal-template-vars"]["properties"]
    seasonal.setdefault("emoji", {"type": "string"})
    seasonal.setdefault(
        "imdb_list_veteran",
        {"type": "string", "pattern": r"^https://(?:www\.)?imdb\.com/list/ls[0-9]+/?$"},
    )

    #
    # Clone only the universe branch; other Defaults keep their original restrictions.
    #
    universe = copy.deepcopy(definitions["simple-dynamic-template-vars"])
    universe["properties"].setdefault(
        "append_data", {"type": "object", "additionalProperties": {"type": "string"}}
    )
    definitions["kometa-config-universe-vars"] = universe
    branch = definitions["kometa-default-collection-path"]["allOf"][0]
    while branch:
        if (
            branch.get("if", {}).get("properties", {}).get("default", {}).get("const")
            == "universe"
        ):
            branch["then"]["properties"]["template_variables"] = {
                "$ref": "#/definitions/kometa-config-universe-vars"
            }
            break
        branch = branch.get("else")
    else:
        raise ValueError(
            "Upstream universe schema changed; review compatibility fixes."
        )

    #
    # Resolution's conditional offsets accept explicit numeric template overrides.
    # Keep the remainder of the overlay schema closed to unknown properties.
    #
    overlay = definitions["template-variables-overlays"]["properties"]
    for key in ("final_horizontal_offset", "final_vertical_offset"):
        overlay.setdefault(key, {"type": "integer"})

    #
    # Secret substitutions are source syntax, not malformed literal Plex addresses.
    # Only the URL value may use a complete placeholder; arbitrary text still fails.
    #
    for name in ("plex-server", "plex-server-lib"):
        definitions[name]["properties"]["url"]["anyOf"].append(
            {"type": "string", "pattern": r"^<<[A-Za-z_][A-Za-z0-9_]*>>$"}
        )
    return schema


def validation_errors(schema: dict, document: dict) -> list:
    """Return validation failures without logging configuration values.

    Args:
        schema: The generated editor schema.
        document: Parsed source configuration, never private runtime output.

    Returns:
        Validation errors for the caller to summarize safely.
    """
    validator = validators.validator_for(schema)
    validator.check_schema(schema)
    return list(validator(schema).iter_errors(document))


def main() -> None:
    """Refresh the ignored editor schema and check all three public config sources."""
    root = Path(__file__).resolve().parents[1]
    image = os.environ.get("KOMETA_IMAGE", "")
    match = re.fullmatch(
        r"kometateam/kometa:(v[0-9]+\.[0-9]+\.[0-9]+)@sha256:[a-f0-9]{64}", image
    )
    if not match:
        raise SystemExit("Run make validate-editor with the pinned KOMETA_IMAGE.")
    version = match[1]
    settings = (root / ".vscode/settings.json").read_text()
    editor_versions = set(
        re.findall(
            r"Kometa-Team/Kometa/(v[0-9]+\.[0-9]+\.[0-9]+)/json-schema/", settings
        )
    )
    if editor_versions != {version}:
        raise SystemExit(
            "Editor schema URLs must match the pinned Kometa runtime version."
        )
    url = f"https://raw.githubusercontent.com/Kometa-Team/Kometa/{version}/json-schema/config-schema.json"
    with urllib.request.urlopen(url, timeout=30) as response:
        schema = build_schema(json.load(response))
    schema["$comment"] = (
        f"Generated by scripts/editor-schema.py from {url}; do not edit."
    )
    target = root / ".vscode/.schemas/config-schema.json"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(schema, indent=2) + "\n", encoding="utf-8")
    yaml = YAML(typ="safe")
    failed = False
    for filename in (
        "config.yml",
        "tests/kometa/config.yml",
        "tests/kometa/collections-config.yml",
    ):
        errors = validation_errors(schema, yaml.load((root / filename).read_text()))
        for error in errors:
            location = "/".join(str(part) for part in error.absolute_path)
            print(f"{filename}: schema {error.validator} failure at {location or '/'}")
        failed = failed or bool(errors)
    if failed:
        raise SystemExit(1)
    print(
        f"Editor schema {version}: all three config files passed; VS Code schema refreshed."
    )


if __name__ == "__main__":
    main()
